language: java
jdk:
   -openjdk8
script: ant build
dist: trusty


addons:
 sonarcloud:
  organization: "ariannafreda12"
  token:
   secure: "travis encrypt 8c21b7886f3058a92dfc0c075ba9fd2674374667"
script:
-ant build
-sonar-scanner