language: java
jdk:
   -openjdk8
script: ant build
dist: trusty


addons:
 sonarcloud:
  organization: "ariannafreda12"
  token:
   secure: travis encrypt 7c183810c30af91f3a1ae556696dc83df4ed2770
script:
-ant build
-sonar-scanner
